app/auth.py
from flask import Blueprint, redirect, flash, render_template, url_for, request
from flask_login import current_user, login_user, logout_user, login_required
from app.forms import RegistrationForm, LoginForm
from app import login_manager, db
from app.models import User, Gender

user = Blueprint(
    'user',
    __name__
)


@user.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect("/")

    form = LoginForm()
    if form.validate_on_submit():
        user = db.session.execute(
            db.select(User).filter_by(email=form.email.data)
        ).scalar()

        if user and user.check_password(password=form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            # TODO: validate value of next with is_safe_url(next)
            flash('Successfully logged-in')
            return redirect(next_page or url_for('charts.home'))
        flash('Invalid email/password combination')
        return redirect("/login")
    else:
        return render_template('login.html', form=form)


@user.route("/logout")
@login_required
def logout():
    logout_user()
    flash('Successfully logged-out')
    return redirect(url_for('user.login'))


@user.route("/register", methods=['GET', 'POST'])
def register():
    """User registration page"""
    form = RegistrationForm()
    if form.validate_on_submit():
        existing_user = db.session.execute(
            db.select(User.id).filter_by(email=form.email.data)
        ).first()
        if existing_user is None:
            gender_id = db.session.execute(
                db.select(Gender.id).filter_by(biology=form.gender.data)
            ).scalar()
            user = User(
                name=form.username.data,
                email=form.email.data,
                gender_id=gender_id,
                birthday=form.birthday.data
            )
            user.set_password(form.password.data)
            db.session.add(user)
            db.session.commit()
            login_user(user)
            flash('Congratulations. You have successfully registered')
            return redirect("/")
        flash('A user already exists with that email address')
        return redirect("/login")
    else:
        return render_template('register.html', form=form)


# Helper Functions
@login_manager.user_loader
def load_user(user_id):
    """Check is user is logged-in on every page load"""
    if user_id is not None:
        return db.session.execute(
            db.select(User).filter_by(id=user_id)
        ).scalar()
    return None


@login_manager.unauthorized_handler
def unauthorised():
    """Redirect unauthorised users to Login page"""
    flash('You must be logged-in to view that page')
    return redirect(url_for('user.login'))

app/charts/routes.py
from flask import Blueprint, render_template, redirect, flash
from flask_login import login_required
from app.models import db, User, Measurement
from app.forms import MeasurementForm

import pandas as pd
import plotly
# import plotly.graph_objects as go
import plotly.express as px
import json


charts = Blueprint(
    'charts',
    __name__,
    template_folder='templates'
)


@charts.route("/", methods=['GET', 'POST'])
@login_required
def home():
    """TODO: Add function doc"""

    # TODO: Get id from session
    id = 1

    record = db.session.execute(
        db.select(User).filter_by(id=id)
    ).scalar()

    # print("**************************************************************")
    # print(f"ID: {record.id}")
    # print(f"Gender: {record.gender.biology}")
    # print(f"Birthday: {record.birthday}")
    # print(f"Measurements: {record.measurements}")
    # for measurement in record.measurements:
    #     print(f"Weight: {measurement.bmi}")
    # print("**************************************************************")

    if record.gender.id == 1:
        sex = "Males"
        df = pd.read_excel('datasets/bmi4age-datatables.xlsx', sheet_name=0)
    else:
        sex = "Females"
        df = pd.read_excel('datasets/bmi4age-datatables.xlsx', sheet_name=1)

    percentiles = [
        '3rd', '5th', '10th', '25th', '50th',
        '75th', '85th', '90th', '95th', '97th'
    ]

    fig = px.line(
        df,
        x="Age",
        y=percentiles,
        height=600,
        title=f"BMI for Age in {sex}, 2-20",
        labels={
            "Age": "Age in Months",
            "value": "BMI",
            "variable": "Percentile"
        },
        template="plotly_white"
    )

    fig.update_yaxes(
        showgrid=True
    )

    graphJSON = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)

    return render_template("index.html", graphJSON=graphJSON)


@charts.route("/add-measurement", methods=["GET", "POST"])
@login_required
def add_measurement():
    """
    BMI Calculator KG = Weight (kg) / Height (m)²
    BMI = [Weight (lbs) / Height (inches)²] x 703
    """
    form = MeasurementForm()
    if form.validate_on_submit():
        id = 1  # TODO: Get id from session
        height = form.height.data
        weight = form.weight.data
        bmi = float(weight)/((float(height)/100) ** 2)

        new_measurement = Measurement(
            user_id=id,
            bmi=bmi
        )
        db.session.add(new_measurement)
        db.session.commit()

        flash('Measurement successfully added')

        return redirect("/")
    else:
        return render_template("measurement.html", form=form)

app/templates/index.html
{% extends "layout.html" %}

{% block title %}
Home
{% endblock %}

{% block main %}
<div id='chart' class='chart' ”></div>

<script src='https://cdn.plot.ly/plotly-latest.min.js'></script>
<script type='text/javascript'>
  var graphs = {{graphJSON | safe }};
  Plotly.plot('chart', graphs, {});
</script>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="initial-scale=1, width=device-width">

  <!-- https://favicon.io/emoji-favicons/money-bag/ -->
  <link href="/static/favicon.ico" rel="icon">

  <!-- stylesheets -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  <link href="/static/styles.css" rel="stylesheet">

  <!-- ui icons and control -->
  <script src="https://kit.fontawesome.com/2e9dae02af.js" crossorigin="anonymous"></script>
  <script src="/static/ui-control.js"></script>

  <title>BMI for Kids: {% block title %}{% endblock %}</title>
</head>

<body class="has-navbar-fixed-top">
  <nav class="navbar is-fixed-top has-shadow" role="navigation" aria-label="main navigation">
    <div class="navbar-brand m-0 p-0">
      <a class="navbar-item" href="/">
        <img src="/static/bmi.png" width="150px">
      </a>

      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        {% if current_user.is_authenticated %}
        <a class="navbar-item" href="/">
          Chart
        </a>

        <a class="navbar-item" href="/add-measurement/{{ session['system'] }}">
          Add Measurement
        </a>
        <a class="navbar-item" href="/manage-data">
          Manage Data
        </a>
        {% endif %}

        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            More
          </a>

          <div class="navbar-dropdown is-boxed">
            <a class="navbar-item">
              About
            </a>
            <hr class="navbar-divider">
            <a class="navbar-item">
              Report an issue
            </a>
          </div>
        </div>
      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            {% if current_user.is_authenticated %}
            <a class="button is-light" href="/logout">
              Log out
            </a>

            {% else %}
            <a class="button is-primary" href="/register">
              <strong>Register</strong>
            </a>
            <a class="button is-light" href="/login">
              Log in
            </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </nav>

  {% if get_flashed_messages() %}
  <div class="notification is-info has-text-centered">
    <button class="delete"></button>
    {{ get_flashed_messages() | join(" ") }}
  </div>
  {% endif %}

  <main>
    {% block main %}{% endblock %}
  </main>
</body>

</html>

app/templates/login.html
{% extends "layout.html" %}

{% block title %}
Login
{% endblock %}

{% block main %}
<section class="section">
  <form action="/login" method="post" class="container column is-half">
    {{ form.csrf_token }}
    <fieldset class="field">
      <!-- TODO: Add font-awesome fonts to forms -->
      {{ form.email.label(class="label") }}
      <p class="control has-icons-left">
        {{ form.email(class="input", placeholder='you@example.com') }}
        <span class="icon is-small is-left">
          <i class="fas fa-envelope"></i>
        </span>
      </p>
      {% if form.email.errors %}
      <ul class="errors">
        {% for error in form.email.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </fieldset>
    <fieldset class="field">
      {{ form.password.label(class="label") }}
      <p class="control has-icons-left">
        {{ form.password(class="input") }}
        <span class="icon is-small is-left">
          <i class="fas fa-lock"></i>
        </span>
      </p>
      {% if form.password.errors %}
      <ul class="errors">
        {% for error in form.password.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </fieldset>
    {{ form.submit(class="button is-primary") }}
  </form>
  <div class="container column is-half">
    <span>Don't have an account?</span>
    <a href="{{ url_for('user.register') }}">Register</a>
  </div>
</section>
{% endblock %}

app/templates/manage-data.html
{% extends "layout.html" %}

{% block title %}
Manage Data
{% endblock %}

{% block main %}
<section class="section">
  <table class="table container is-fullwidth is-narrow">
    <thead>
      <tr>
        <th>Date of Measurement</th>
        <th>BMI</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for d in data %}
      <tr>
        <td>{{ d.timestamp.strftime('%d %b %Y') }}</td>
        <td>{{ d.bmi | round(2, 'common') }}</td>
        <td>
          <form action="/delete-data/{{ d.id }}" method="post">
            {{ form.csrf_token }}
            {{ form.submit(class="button is-danger") }}
          </form>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</section>
{% endblock %}

app/templates/measurement.html
{% extends "layout.html" %}

{% block title %}
Add Measurement
{% endblock %}

{% block main %}
<!--
TODO: Allow users to choose whether to work in imperial or metric
-->
<section class="section">
  <form action="/add-measurement/{{ session['system'] }}" method="post" class="container column is-half">
    {{ form.csrf_token }}
    <fieldset class="field">
      {{ form.date.label(class="label") }}
      <p class="control has-icons-left">
        {{ form.date(class="input") }}
        <span class="icon is-small is-left">
          <i class="fas fa-calendar"></i>
        </span>
      </p>
      {% if form.date.errors %}
      <ul class="errors">
        {% for error in form.date.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </fieldset>
    <fieldset class="field">
      {{ form.height.label(class="label") }}
      <p class="control has-icons-left">
        {{ form.height(class="input") }}
        <span class="icon is-small is-left">
          <i class="fas fa-ruler-vertical"></i>
          <i class="fas fa-person"></i>
        </span>
      </p>
      {% if form.height.errors %}
      <ul class="errors">
        {% for error in form.height.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </fieldset>
    <fieldset class="field">
      {{ form.weight.label(class="label") }}
      <p class="control has-icons-left">
        {{ form.weight(class="input is-normal") }}
        <span class="icon is-small is-left">
          <i class="fas fa-weight-scale"></i>
        </span>
      </p>
      {% if form.weight.errors %}
      <ul class="errors">
        {% for error in form.weight.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </fieldset>
    {{ form.submit(class="button is-primary") }}
  </form>
  <div class="container column is-half">
    {% if session['system'] == 'imperial' %}
    <a href="{{ url_for('charts.add_measurement', system='metric') }}">Switch to Metric</a>
    {% else %}
    <a href="{{ url_for('charts.add_measurement', system='imperial') }}">Switch to Imperial</a>
    {% endif %}
  </div>
</section>
{% endblock %}

app/templates/register.html
{% extends "layout.html" %}

{% block title %}
Register
{% endblock %}

{% block main %}

<section class="section">
  <form action="/register" method="post" class="column container is-half">
    {{ form.csrf_token }}
    <fieldset class="field">
      {{ form.username.label(class="label") }}
      <p class="control has-icons-left">
        {{ form.username(class="input", placeholder='Username') }}
        <span class="icon is-small is-left">
          <i class="fas fa-user"></i>
        </span>
      </p>
      {% if form.username.errors %}
      <ul class="errors">
        {% for error in form.username.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </fieldset>
    <fieldset class="field">
      {{ form.email.label(class="label") }}
      <p class="control has-icons-left">
        {{ form.email(class="input", placeholder='youremail@example.com') }}
        <span class="icon is-small is-left">
          <i class="fas fa-envelope"></i>
        </span>
      </p>
      {% if form.email.errors %}
      <ul class="errors">
        {% for error in form.email.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </fieldset>
    <fieldset class="field">
      {{ form.birthday.label(class="label") }}
      <p class="control has-icons-left">
        {{ form.birthday(class="input") }}
        <span class="icon is-small is-left">
          <i class="fas fa-calendar"></i>
        </span>
      </p>
      {% if form.birthday.errors %}
      <ul class="errors">
        {% for error in form.birthday.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </fieldset>
    <fieldset class="field">
      {{ form.gender.label(class="label") }}
      <div class="control has-icons-left">
        <div class="select">
          {{ form.gender(class="input") }}
        </div>
        <div class="icon is-small is-left">
          <i class="fas fa-person"></i>
          <i class="fas fa-person-dress"></i>
        </div>
      </div>
      {% if form.gender.errors %}
      <ul class="errors">
        {% for error in form.gender.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </fieldset>
    <fieldset class="field">
      {{ form.password.label(class="label") }}
      <p class="control has-icons-left">
        {{ form.password(class="input") }}
        <span class="icon is-small is-left">
          <i class="fas fa-lock"></i>
        </span>
      </p>
      {% if form.password.errors %}
      <ul class="errors">
        {% for error in form.password.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </fieldset>
    <fieldset class="field">
      {{ form.confirmation.label(class="label") }}
      <p class="control has-icons-left">
        {{ form.confirmation(class="input") }}
        <span class="icon is-small is-left">
          <i class="fas fa-lock"></i>
        </span>
      </p>
      {% if form.confirmation.errors %}
      <ul class="errors">
        {% for error in form.confirmation.errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </fieldset>
    {{ form.submit(class="button is-primary") }}
  </form>
  <div class="container column is-half">
    <div>
      <span>Already have an account?</span>
      <a href="{{ url_for('user.login') }}">Log in.</a>
    </div>
  </div>
  <section>
    {% endblock %}